apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgrn-stack-chart.fullname" . }}-configmap
  labels:
    {{- include "mgrn-stack-chart.labels" . | nindent 4 }}
data:
  config.toml: |
{{ .Files.Get "config.toml" | indent 4 }}